[workspace]
members = [
  "crates/aptos-ext",
  "crates/aptos-move-graphql-scalars",
  "crates/aptos-move-graphql-schema",
  "crates/aptos-move-graphql-test-helpers",
]
resolver = "2"

[workspace.package]
edition = "2024"
publish = false
authors = ["Daniel Porteous <daniel@dport.me>"]
homepage = "https://dport.me"
license = "Apache-2.0"
repository = "https://github.com/banool/aptos-tools"

[workspace.dependencies]
# Internal dependencies
aptos-move-graphql-scalars = { path = "crates/aptos-move-graphql-scalars" }
aptos-move-graphql-schema = { path = "crates/aptos-move-graphql-schema" }
aptos-move-graphql-test-helpers = { path = "crates/aptos-move-graphql-test-helpers" }

# Regular dependencies
anyhow = "1.0.98"
async-graphql = { version = "6.0.1", features = ["dynamic-schema"] }
async-trait = "0.1.68"
clap = { version = "4.3.9", features = [
    "derive",
    "env",
    "unstable-styles",
    "wrap_help",
] }
once_cell = "1.10.0"
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = { version = "1.0.81", features = [
    "preserve_order",
    "arbitrary_precision",
] }
tokio = { version = "1.35.1", features = ["full"] }

# aptos dependencies
aptos = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
aptos-api-types = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
aptos-framework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
async-graphql-reverse = { git = "https://github.com/tacogips/async-graphql-reverse.git", rev = "2e5e7758051f7ba57da3940e5bc75a4e80badf4c" }
move-binary-format = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
move-core-types = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
move-package = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }
move-resource-viewer = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "83755c454d95df6e125900cb34662f364ce2cc95" }

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
jemalloc-sys = { git = "https://github.com/aptos-labs/jemalloc-sys-shim", rev = "e0920246dd74303fab9a14b990768c6ac990a59b" }

[profile.cli]
inherits = "release"
debug = false
opt-level = "z"
lto = "thin"
strip = true
codegen-units = 1
